### ISSUE TITLE
获取access_token方式只适合单机应用

### ISSUE THREAD

**Issue by Sunzhuokai** [RabbitTeam/WeiXinSDK#2]
这种方式不易扩展，应该有一个控制中心来获取access_token

**Comment by majian159** [comment]
access_token现在是通过AccountModel类里面的一个委托来获取的，AccountModel则是通过依赖注入服务来注入的，请问你在使用中觉得哪里不方便呢？

**Comment by Sunzhuokai** [comment]
对于web集群这样一定不靠谱的。保存在内存里每台机器都维护自己的token生命周期会乱的

**Comment by Sunzhuokai** [comment]
说的是commonService

**Comment by majian159** [comment]
你误解了，ICommonService中的GetAccessToken是对应微信文档上的获取方式，而不是在使用过程中的AccessToken，使用过程中的AccessToken是通过AccountModel中的GetAccessToken委托来得到的。
我们已经在分布式的环境上使用了这套SDK，而做法就是重新实现IDependencyResolver接口，在新的实现类中构建AccountModel类，设置GetAccessToken的委托从redis或webapi中读取accesstoken。

**Comment by Sunzhuokai** [comment]
恩，是我有些误解了，不过我觉得如果是微信api文档上的实现应该不需要存在字典里吧，直接调用就可以了。缓存数据应该由接入方进行控制吧，比如先通过这个接口获取到token然后缓存到redis里。commonService只作为apigateway使用

**Comment by majian159** [comment]
token的缓存是为了提供简单的sdk所做的工作，因为大部分初级应用者还不需要自己重新构建AccountModel，主要还是为了初级使用者所做的一些工作，在GetAccessToken方法中sdk提供了参数ignoreCached来忽略缓存。
